services:
  a4video:
    restart: unless-stopped
    build: .
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./errors:/usr/share/nginx/html/errors:ro
    networks:
      - net

networks:
  net:
    external: true
