services:
  fastapi:
    restart: unless-stopped
    build: ./backend
    volumes:
      - ./backend/data:/app/data
    networks:
      - net
    expose:
      - "8001"

  a4video:
    restart: unless-stopped
    build: .
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./errors:/usr/share/nginx/errors:ro
    networks:
      - net
    depends_on:
      - fastapi
    ports:
      - "8000:8000"

networks:
  net:
    external: true
