services:
  a4video:
    restart: unless-stopped
    build: .
    volumes:
      - ./public:/usr/share/nginx/html
      - ./errors:/usr/share/nginx/html/errors
    networks:
      - net

networks:
  net:
    external: true
