server {
    listen 8000;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        if ($request_uri ~ ^/(.*)\.html(\?|$)) {
            return 302 /$1;
        }
        try_files $uri $uri.html $uri/ =404;
    }

    error_page 403 /errors/403.html;
    error_page 404 /errors/404.html;
    error_page 400 401 402 /errors/4xx.html;
    error_page 500 502 503 504 /errors/50x.html;

    location /errors/ {
        internal;
    }
}

server_tokens off;
